version: '3.8'
services:
  web:
    image: cr.yandex/crpqjs9qp1emch06cj07/pythonapp:1.0.0
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_TABLE=${DB_TABLE}

networks:
  backend:
    driver: bridge

