version: '3.8'
services:
  db:
    image: mysql:8
    #networks:
      #backend: {}
        #ipv4_address: 172.20.0.10
    restart: on-failure
    env_file:
      - enviremoment.env
    environment:
      - MYSQL_ROOT_PASSWORD=superstrong
      - MYSQL_DATABASE=ipaddr
      - MYSQL_USER=python
      - MYSQL_PASSWORD=strongest

  web:
    image: cr.yandex/crpqjs9qp1emch06cj07/pythonapp:1.0.1
    #networks:
      #backend: {}
        #ipv4_address: 172.20.0.5
    restart: always
    #env_file:
      #- enviremoment.env
    environment:
      - DB_HOST=db
      - DB_USER=python
      - DB_PASSWORD=strongest
      - DB_NAME=ipaddr
      - DB_TABLE=query
    depends_on:
      - db

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24



