version: '3.8'
services:
  db:
    image: mysql:8
    networks:
      - backend
        #ipv4_address: 172.20.0.10
    restart: on-failure
    env_file:
      - envdb.env

  web:
    image: cr.yandex/crpqjs9qp1emch06cj07/pythonapp:1.0.1
    networks:
      - backend
        #ipv4_address: 172.20.0.5
    restart: always
    env_file:
      - envpy.env
    depends_on:
      - db

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
         aux_addresses:
           web: 172.20.0.5
           db: 172.20.0.10



