version: '3.8'
services:
  web:
    image: cr.yandex/crpqjs9qp1emch06cj07/pythonapp:1.0.0
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    #env_file:
      #- enviremoment.env
    environment:
      - DB_HOST=172.20.0.10
      - DB_USER=pythonapp
      - DB_PASSWORD=strongest
      - DB_NAME=ipaddr
      - DB_TABLE=query
      - MYSQL_ROOT_PASSWORD=superstrong
    depends_on:
      - db

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    env_file:
      - enviremoment.env
    expose:
      - "3306"

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16



